version: '3.8'
services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  postgres_data:

networks:
  spring-network:
